angular.module('app').constant('events', {
  message: {
    _ADD_ERROR_MESSAGE_: '_ADD_ERROR_MESSAGE_',
    _CLEAR_ERROR_MESSAGES_: '_CLEAR_ERROR_MESSAGES_',
    _ERROR_MESSAGES_UPDATED_: '_ERROR_MESSAGES_UPDATED_',
    _ADD_USER_MESSAGE_: '_ADD_USER_MESSAGE_',
    _CLEAR_USER_MESSAGES_: '_CLEAR_USER_MESSAGES_',
    _USER_MESSAGES_UPDATED_: '_USER_MESSAGES_UPDATED_',
    _DISPLAY_POPUP_: '_DISPLAY_POPUP_',
    _DISPLAY_DIALOG_: '_DISPLAY_DIALOG_',
    _DISPLAY_CONFIRMATION_: '_DISPLAY_CONFIRMATION_',
    _USER_RESPONDED_: '_USER_RESPONDED_',
    _CLEAR_NOTIFICATIONS_: '_CLEAR_NOTIFICATIONS_'}
});
